### ISSUE TITLE
direct usage of schema.org

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/CPOV#10]
This strong dependency on schema.org at the level of European core vocabularies is not really clear to me. 
For contact points there is vcard maintained by W3C and used in DCAT-AP. 
I know that OpeningHoursSpecification is something useful but probably the European Commission can define it’s own concept that can then  align with schema.

What I am saying is that the objectives of EU Core Vocs for the public sector can be different from the objectives of an ontology mainly maintained by Google for SEO purposes . The wonderful thing of linked data is that we can link also ontologies but for sustainability and EU work in the public sector purposes, probably this strategy can be discussed a bit further.

**Comment by pebran** [comment]
Use of elements from schema.org must be done with caution. Both domain and range has in the past changed and from time to time, an element has been deprecated and replaced with another almost similar one.  
BUT…classes like ContactPoint and Opening HoursSpecification has been stable for some time now and are very useful. For that reason, I would like to keep these in the CV.

**Comment by giorgialodi** [comment]
Yes, probably because that part of schema.org is derived from GoodRelations ontology, if I remember correctly. I still strongly believe that we can define our concept in the context of the EU vocabularies still maintaining the linking with schema.org. In fact, we can always align to schema.org and many other ontologies if we wish.

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-05-20, it was agreed that classes and attributes that are reused from schema.org will be recreated in the SEMIC namespace, also taking into account the SEMIC naming conventions.

**Comment by aidig** [comment]
When will the above decision be reflected in the published profile and diagram (which still reuses ContactPoint from schema.org)? Also, presumably the decision to refrain from using schema.org directly will be applied to all application profiles created within the context of SEMIC?

As a general question, are the published Core Vocs diagrams and html specifications up-to-date with respect to the decisions made in the previous webinars?

**Comment by danbri** [comment]
I am responsible for Schema.org. 

I'd say first of all, make sure you can represent whatever you have requirements to represent.

If that corresponds to concepts we've modelled in Schema.org, then we would all benefit to have any equivalences documented and accessible to humans and to machines. It should be possible to do this without anything being strictly dependent on anything else, if that is important here: i.e. just describe mappings.

Schema.org has recently joined Dublin Core's Advisory Board, and I arranged this in part to help foster better links and mappings between high profile schemas. We could look at nudging some of our definitions in ways that help with SEMIC vocabularies too, perhaps. The other obvious definitions to map and converge are Schema.org's Person and FOAF's Person type. They are essentially the same idea with slightly different words, so I plan to have them use the same form of words. 

* [Core voc Person](https://semiceu.github.io/Core-Person-Vocabulary/releases/2.00/#Person): "An individual person who may be dead or alive, but not imaginary."
* [FOAF Person](https://xmlns.com/foaf/0.1/#term_Person): "The Person class represents people. Something is a Person if it is a person. We don't nitpic about whether they're alive, dead, real, or imaginary."
* [Schema.org Person](https://schema.org/Person): "A person (alive, dead, undead, or fictional)."

The most obvious clash here is on whether imaginary and fictitious persons are included, as is pointed out in your [spec](https://semiceu.github.io/Core-Person-Vocabulary/releases/2.00/#Person).

Can you help me understand the goal of the non-imaginary constraint? Is the vocabulary supposed to be inapplicable to describing media, creative and cultural heritage content?

For example, https://www.wikidata.org/entity/Q25749 is an art work created by the Person https://www.wikidata.org/entity/Q5577 and depicting the Person https://www.wikidata.org/entity/Q302

Wikidata describes Jesus in several ways, including "human who may be fictional". From both Schema.org and FOAF perspective we prefer to disentangle such debates from using the term "Person" in graph data. Are there usecases that we're missing, or just does it seem too scruffy to allow a single simple Person type to cover such a broad set of situations?

**Comment by makxdekkers** [comment]
Hi Dan, many thanks for your comment! Good points.

On the issue of mappings, we could look at possibilities to document equivalences with external terms like the ones in schema.org and Wikidata, but we need to be careful about maintainability of such mappings. Apart from that, the SEMIC action would welcome synergies concerning alignment on the formal aspects of vocabulary management, such as style sheets etc, not only with W3C but also Schema.org.

Concerning the limitation we have applied to Core Person, to only include ‘real’ persons: our primary use case is related to government data and services – such as data in a base registry or printed on a passport – and in that context one is not concerned with imaginary or fictional characters. Core Person explicitly asserts “_Person:Person [is] a subclass of both foaf:Person and schema:Person which both cover imaginary characters as well as real people_” to make that distinction clear.

**Comment by EmidioStani** [comment]
As discussed in the webinar 09/11/2021 the classes of ImageObject, ContactPoint and OpeningHoursSpecification will be moved under Core Vocabularies namespace

**Comment by danbri** [comment]
May I ask if Schema.org’s license terms (CC-BY-SA3, http://creativecommons.org/licenses/by-sa/3.0/) fit with your goals here, regarding schema.org, dependencies, shared definitions etc.

For schema.org It would be challenging to relicense everything but I am looking into options for making a more liberal license for certain core and/or popular terms, eg by rewriting the definitions to capture the same idea in fresh words.

re popular/core, https://twitter.com/httparchive/status/1461423045059485703?s=21 may be of interest
