### ISSUE TITLE
Representing the vocabulary in UML/HTML

### ISSUE THREAD

**Issue by aidig** [SEMICeu/CPOV#11]
**UML**

- It would be helpful, if the UML visualisation of the core vocabularies always included prefixes in the UML names of all classes and all properties so that the element provenance is visible in the diagrams too (like in W3C vocabs). 
- Also, it is a great idea to provide labels in natural language (i.e not camel case) in addition to the qualified names in the html spec (e.g. ‘alternative label’ for ‘skos:altLabel’), but in the UML-diagram please apply the latter for the UML name for greater precision and ease of semantic interpretation. Alternative labels can also be added to the UML-model by using tagged values or Alias (combined with a 'show both UML name and alias' in the diagram setting if required in png-distribution).

**HTML**

- The Core Voc html specification(s) should include a list of namespaces and prefixes applied in the document(s).
- In the property tables, it would be helpful if the values of the ‘Expected’ range column where not ‘translated’ to labels such as ‘Text’ when rdf:langString would be a more precise short form of http://www.w3.org/1999/02/22-rdf-syntax-ns#langString, for instance

Apologies for creating identical issues in the various repos, but it currently seems to be the only way to make general comments that applies to the all the revised core vocs ;-)

**Comment by aidig** [comment]
Also, it maybe a matter of personal preference, but I think it would be great if the order of elements in the core vocabulary specs were not alphabetical but model-oriented, ie. making the Person/LegalEntity/PublicOrganisation/Location class - respectively - the first described element rather than Address.

**Comment by aidig** [comment]
Another general suggestion: It would be very helpful if the vocabularies included some basic (dummy) example descriptions of how to use the Person/LegalEntity/PublicOrganisation/Location vocabularies. (Like the previous core vocabularies specification did in the Appendix)

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-05-20, a suggestion was made to look into the [EUROVOC](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/eurovoc) and [IATE](https://iate.europa.eu/home) terminology.

**Comment by aidig** [comment]
> During the Core Vocs webinar dd. 2021-05-20, a suggestion was made to look into the [EUROVOC](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/eurovoc) and [IATE](https://iate.europa.eu/home) terminology.

The above reply does not seem to be related to the issue of representing the vocabulary in UML/HTML?
