### ISSUE TITLE
cpov:PublicOrganisation subClassOf 

### ISSUE THREAD

**Issue by aidig** [SEMICeu/CPOV#14]
The class cpov:PublicOrganisation is currently defined as a subClassOf org:Organization, but what is the argument for not defining it as an org:FormalOrganization (which is also reused in Core Business Vocabulary)? The W3C definition and provided examples seem to include public organisations, but there might be other reasons for not reusing this class?

> **org:FormalOrganization** 
> An Organization which is recognized in the world at large, in particular in legal jurisdictions, with associated rights and responsibilities. Examples include a corporation, charity, government or church.

source: http://www.w3.org/ns/org#FormalOrganization

**Comment by mayaborges** [comment]
I cannot find any requirement that org:FormalOrganization be legal entities. It is certainly not a part of the definition. 

I find it hard to imagine a PublicOrganisation that is not recognized in the jurisdiction where it exists. And having rights and/or responsibililties also so seem very much in line with being a PublicOrganisation. So I really do not understand why PublicOrganisation cannot be a subclass of org:FormalOrganization.

**Comment by aidig** [comment]
In the communication during the development of The Organization Ontology, it was also noted that "Formal" is ambiguous and discussed what the purpose FormalOrganization was:
https://lists.w3.org/Archives/Public/public-lod/2010Jun/0103.html
https://lists.w3.org/Archives/Public/public-lod/2010Jun/0110.html
https://lists.w3.org/Archives/Public/public-lod/2010Jun/0120.html

**Comment by EmidioStani** [comment]
As discussed in the webinar of 09/11/2021 the subclass relation will not change, as such change does not have an impact per se.
