### ISSUE TITLE
Wrong objectproperty 'identifier' used

### ISSUE THREAD

**Issue by pebran** [SEMICeu/CPOV#17]
A property named ‘identifier’ - going from the class ‘PublicOrganization’ to the class ‘Identifier’ - seems to be defined as http://www.w3.org/ns/org#identifier . This would be wrong and should probably have been http://www.w3.org/ns/adms#identifier .

**Comment by EmidioStani** [comment]
During the webinar of 9/11/2021 it was agreed to used adms:identifier
