### ISSUE TITLE
Adding class to define a public authority organisation

### ISSUE THREAD

**Issue by pebran** [SEMICeu/CPOV#18]
The PublicOrganization class is useful as a general class for describing any type of public organization. However, we have a need for more precise and specific defined classes for public authorities. 
We therefore propose that a new class is added – a class that is a subclass of both PublicOrganizatin and of org:FormalOrganization. We call the class PublicAuthorityOrganisation, or alternatively just PublicAuthority. 

![billede](https://user-images.githubusercontent.com/391743/143304696-41336a66-b5b6-42a8-9424-e0c1755aa0ee.png)

The class can – if agreed – be further specialized in the three classes LocalPublicAuthority, RegionalPublicAuthority and StatePublicAuthority.

 
![billede](https://user-images.githubusercontent.com/391743/143304681-988908e3-4f25-4e06-b846-6e14970dcbbc.png)

Regards,
Peter Bruhn Andersen
Danish Agency for Digitisation

**Comment by EmidioStani** [comment]
During the webinar of 02/12/2021 it was agreed to keep this issue open until a clear use case was defined.

In the  last webinar it was presented a new way to create use cases:
https://github.com/SEMICeu/CPOV/issues/new?assignees=&labels=use_case&template=use-case-template.yml&title=%5BUse+case%5D%3A+

**Comment by EmidioStani** [comment]
Stale issue, it can be closed and new use case opened
