### ISSUE TITLE
CPSV-AP / CPOV consistency: Contact page to be added in ContactPoint

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPOV#24]
As per issue [CPSV-AP#57](https://github.com/SEMICeu/CPSV-AP/issues/57), ContactPoint should be updated with the contactPage property

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to add contactPage property to the Core Voc::ContactPoint class to align with CPSV-AP.
