### ISSUE TITLE
Merging CPV, CPOV, CBV into one single CAGV

### ISSUE THREAD

**Issue by paulakeen** [SEMICeu/CPOV#4]
Please see CPV [Issue #6](https://github.com/SEMICeu/Core-Person-Vocabulary/issues/6)

**Comment by EmidioStani** [comment]
During the webinar of 02/12/2021, it, it was decided to just have a consolidated diagram which can be found at: https://github.com/SEMICeu/CPOV/tree/master/releases/2.00
