### ISSUE TITLE
Formal Framework is replaced by eli:LegalResource

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/CPOV#5]
The CPOV reuses cpsv:FormalFramwork. That class is however changed to eli:LegalResource [within CPSV-AP](https://github.com/catalogue-of-services-isa/CPSV-AP/blob/master/releases/2.2.1/CPSV-AP%20Specification%20v2.2.1%20-%20PNG.png). We would like to raise the question here whether we should do the same within CPOV.

Also note that CCCEV v2.0.0 is proposing a new class [ReferenceFramework](https://semiceu.github.io/CCCEV/releases/2.00/#Reference%20Framework).

**Comment by giorgialodi** [comment]
I agree with this comment. We need to be uniform across the Core Vocabularies on this point reusing, within the same context .already existing concepts.

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-05-20, there was an agreement regarding the above proposition.

**Comment by EmidioStani** [comment]
During the webinar of 9/11/2021 there was an agreement to reuse ReferenceFramework from CCCEV as it is broader than eli:LegalResource
