### ISSUE TITLE
use of address property

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/CPOV#6]
You cannot use address of CLV to link the organisation to the CLV:Address unless you mean the a public organisation is a location (and it is not. It is an agent. The site  of a public organisation can be seen as a location that as an address. Is it not a registeredAddress? A public organisation is typically registered in some central registry).
This issue is related to issue https://github.com/SEMICeu/Core-Location-Vocabulary/issues/8 and https://github.com/SEMICeu/Core-Location-Vocabulary/issues/7

**Comment by dimi-schepers** [comment]
Please see the comment made in issue https://github.com/SEMICeu/Core-Location-Vocabulary/issues/7#issuecomment-843915663
