### ISSUE TITLE
OrganizationalUnit and use of s or z in the word "Organisation"

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/CPOV#8]
Is the OrganizationalUnit defined in the org ontology from W3C? 
In the diagram is not specified nor it is in the description.
If it is a subclass of org:Organization it is likely that also OrganizationalUnit comes from that Web standard. If so I would better specify this in the diagram and in the related descriptions.

There is also an issue on the use of s and z in the word Organisation. In W3C Org they use z while the title of the vocabulary is Core Public Organisation with the s. Probably it is better to be uniform here :)

**Comment by dimi-schepers** [comment]
Yes, OrganizationUnit is indeed from the ORG ontology. I've clarified this in the diagram and description. Thanks for spotting!

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-05-20, it was agreed to use British English everywhere unless something is reused from another vocabulary or ontology that is written in American English.

**Comment by EmidioStani** [comment]
Confirmed with webinar 09/11/2021
