### ISSUE TITLE
ChangeEvent and its subclass

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/CPOV#9]
In general the new CPOV model did not change that much wrt to its previous version.

One point probably not very clear was that there is just one subclass for the ChangeEvent. This is difficult to understand IMHO.
Either we include all the possible change events that may occur to public organisations (there is not only the foundational event but also the merging or others) or, since it is a core vocabulary, we use just ChangeEvent class, leaving any specializations for possible application profiles.

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-05-20, some voices were in favour of creating a type property on the Change Event allowing for a controlled vocabulary on the different change events. Others were however in favour of keeping the subclasses. 

Someone was able to to inform the Working Group that the Foundation Event class was explicitly added at the time of creation of the first version of CPOV, as it was seen as paramount for the existence of a Public Organisation. Also the relationship to the Formal Framework that contains the legal basis for the foundation of the Public Organisation plays a role in this. This information will be added to the usage note.

**Comment by EmidioStani** [comment]
In the webinar of 09/11/2021 it has been agreed to remove the subclass relation between ChangeEvent and FoundationEvent

**Comment by jpmckinney** [comment]
For historical completeness: FoundationEvent had been exceptionally added for the following reason. For a "change" to occur, there needs to be a thing that undergoes change. But prior to foundation, there exists no organization; there is no organization to which a change is being made. It is incoherent to state, for example, that Acme Inc changed from not existing to existing; something that doesn't exist cannot change. At a stretch, it is the "state of the world" that is changing, when a new organization is founded – but all other change events are scoped to the specific organization, not to the "world".

The class was added to address this semantic issue.

That said, all models need to fudge reality and logic a bit, so I don't mind its removal.
